
local function help()
	print([[
rocale-cli
A command-line tool for building, uploading, and running Roblox projects in Open Cloud.

USAGE:
  rocale-cli <command> [options]

COMMANDS:
  run      Build, upload, and run a Roblox project in Open Cloud.
  help     Show this help message.
  version  Show version.

For more information about a command, run: rocale-cli <command> --help
]])
end

return help
